Question5: create both button "back" and "submit".
CodeforAustralia/council-emissions-calculator-spike pull request #20
Opened 2021-09-14 05:53 UTC by bhagya099

2021-09-15 12:14 UTC, hqtan requested changes
Hi @bhagya099 !
Many thanks for your PR! :bow: 
I tested your changes on the preview site, and noticed that the form response for Question 5  isn't being saved when the 'Back' button was clicked; I have given some suggestions to remedy the problem. Please review and fix.

Thank you!

2021-09-15 12:14 UTC, hqtan commented on pages/form/Question5.js
> +  const [incentive, setIncentive] = useState(answers.incentive);
I don't think we capture anything with `incentive` variable in Question 5; the response for Question 5 should be captured in `department` variable, right?
So I think you can remove this line.
```suggestion
```

2021-09-15 12:14 UTC, hqtan commented on pages/form/Question5.js
> +  const saveAnswers = () => setAnswers((prev) => ({ ...prev, incentive }));
`saveAnswers` should be saving the response in `department` variable, not `incentive`; you could inadvertently be overwriting users' response in Question 4 !
```suggestion
  const saveAnswers = () => setAnswers((prev) => ({ ...prev, department }));
```

2021-09-15 22:50 UTC, hqtan commented
@bhagya099 ,

Another thing I noted is the use of single quotes (') for quotations in the changes.
The general convention in our codebase is to use double quotes (") - you can confirm that by viewing the quotations in other form pages.
Please update the PR to use double quotes for quotations.

Thanks! :bow:

2021-09-15 23:00 UTC, hqtan commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEV: [SML] update page 5](https://trello.com/c/lj5HHd1L/193-dev-sml-update-page-5)

2021-09-16 05:57 UTC, bhagya099 commented
@hqtan,

Thank you for your feedback. I will do changes.

2021-09-25 00:59 UTC, hqtan approved these changes

2021-09-25 01:00 UTC, hqtan approved these changes
:+1:

2021-09-25 01:00 UTC, merged