Removed background colour for and set box shade
CodeforAustralia/council-emissions-calculator-spike pull request #246
Opened 2023-02-15 04:50 UTC by Amutha37

## Overview of the Pull Request:
Removed background colour for Distribution of Commute distance component and add box shade for Distance travelled by mode of transport.

The two component had been sitting on one background colour which does not make sense however, I have combine Distance travelled by mode of transport and the Invidual Method chart under one roof. It will make more sense with the background greyed. 

## link to Trello card or Github issue

https://trello.com/b/iPHuVc0J/civic-makers-2023

## How Has This Been Tested?
- Tested preview on localhost:3000/results desired look achieved

## Pull Request Checklist:

Make sure the following checkboxes`[ ]` are checked with `x` before sending your PR -- thank you!

- [✔️] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [✔️] Is your pull request up-to-date with `main` branch?
- [ ?] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?  No have questions from the mentioned in PR243
- [nil ] Have you written instructions on how to test that your changes work as expected?
- [ ✔️ Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

2023-02-16 11:57 UTC, hqtan requested changes

2023-02-16 11:57 UTC, hqtan commented on pages/results.js
> +      <ResultContentSection isShaded={false}>
Hi @Amutha37 ,

The background color should not have been removed from the 'Distribution of commute distance' section of results page.

Please review the [Figma designs](https://www.figma.com/file/opEaLsTMNJjhKHx3KNXRe6/How-to-calculate-page-hand-off?node-id=2624%3A38592) to confirm.

2023-02-16 20:58 UTC, Amutha37 commented on pages/results.js
> +      <ResultContentSection isShaded={false}>
I will fix this and leave it as it was earlier.

2023-02-17 11:16 UTC, hqtan approved these changes
thx for making the changes @Amutha37 !

lgtm 👍🏽

2023-02-17 23:35 UTC, OlaShabalina approved these changes

2023-02-18 09:00 UTC, merged