Changes made for progress bar to be responsive.
CodeforAustralia/council-emissions-calculator-spike pull request #25
Opened 2021-09-21 00:57 UTC by Amutha37

Please view the progress bar changes made for responsive screen. I need discuss about the text on checkbox in today's meeting.

2021-09-22 23:02 UTC, hqtan requested changes
Hi @Amutha37 , Thx for the PR :bow:

I really like what you've done to the progress bar :heart_eyes:. The length of the progress bar seems more aligned with other components on each page.

I've pointed out a few other things in the code to bring to your attention.

Just for future reference, it would have been nice to see all the changes from y
our [earlier PR#24](https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/24) sorted out and merged in, rather than having the changes from PR#24 now brought into this PR; it's not as easy for the reviewer to tease out what recommendations from PR#24 that you have acted/not acted upon... but it's done, so let's move on this time round :smile:

2021-09-22 23:02 UTC, hqtan commented on styles/globals.css
> +  } */
please remove commented out code
```suggestion
```

2021-09-22 23:09 UTC, hqtan commented
@batteries76 , @ymloh ,

what do you think about the changes related to making the progress bar responsive? 
I think I prefer this to #26  ... (but I'm not a frontend dev, so my opinion here may not matter as much :sweat_smile: )

for comparison: 
- here's a screenshot of progress bar for this PR:
![image](https://user-images.githubusercontent.com/4408259/134433445-f0320257-ddb9-4194-8457-be99547f8ca7.png)

- here's a screenshot of progress bar for #26
![image](https://user-images.githubusercontent.com/4408259/134433580-4a7f33cd-d82e-43d3-9c4d-c9672236ceaa.png)

2021-09-23 06:06 UTC, Amutha37 commented on pages/form/Question1.js
> +        <LinkButton href="/" onClick={saveAnswers} variant="outline">
Will create a separate PR for <BackButton>

2021-09-23 06:10 UTC, Amutha37 commented on pages/form/Question1.js
> +        className="responsivebar"
Removed line 64 and 54.

2021-09-23 06:11 UTC, Amutha37 commented on pages/form/Question1.js
> +
Removed line 94 and 95.

2021-09-23 06:11 UTC, Amutha37 commented on pages/form/Question1.js
> +  createBreakpoints,
Removed line 16.

2021-09-23 06:11 UTC, Amutha37 commented on pages/form/Question1.js
> +// });
Removed all the commented lines.

2021-09-23 06:55 UTC, Amutha37 commented on styles/globals.css
> +  } */
Removed all the commented line.

2021-09-23 07:20 UTC, Amutha37 commented on pages/form/Question1.js
> +        <LinkButton href="/" onClick={saveAnswers} variant="outline">
Can the person who created teh LinkButton component look at this request.

2021-09-23 23:36 UTC, hqtan commented
Hi @Amutha37 

Are you able to remove the changes for the download button in the results page, and move that to a separate PR please?

2021-09-27 07:12 UTC, Amutha37 commented
Hi Qing,

I will do that tomorrow. Sorry, I just saw your message.

Amutha


On Fri, 24 Sep 2021 at 9:37 am, hqtan ***@***.***> wrote:

> Hi @Amutha37 <https://github.com/Amutha37>
>
> Are you able to remove the changes for the download button in the results
> page, and move that to a separate PR please?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeforAustralia/council-emissions-calculator-spike/pull/25#issuecomment-926239718>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP724Q7JQZQMDVJEKA5OHNDUDO22JANCNFSM5ENFG36Q>
> .
>
>
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-02 01:42 UTC, closed without merging